[build]
  command = "npm run build"
  publish = "dist"
  NODE_VERSION = "18"

[context.production.environment]
  VITE_API_URL = "https://samngoclinh-back.onrender.com/api"

[context.deploy-preview.environment]
  VITE_API_URL = "https://samngoclinh-back.onrender.com/api"

[context.branch-deploy.environment]
  VITE_API_URL = "https://samngoclinh-back.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 