[build]
  command = "npm run build"
  publish = "dist"
  NODE_VERSION = "18"

[context.production.environment]
  VITE_API_URL = "http://localhost:8080/api/"

[context.deploy-preview.environment]
  VITE_API_URL = "http://localhost:8080/api/"

[context.branch-deploy.environment]
  VITE_API_URL = "http://localhost:8080/api/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 